/* TinyMCE Chinese (Simplified) language pack */
tinymce.addI18n('zh_CN', {
  "File": "文件",
  "Edit": "编辑",
  "Insert": "插入",
  "View": "查看",
  "Format": "格式",
  "Table": "表格",
  "Tools": "工具",
  "Help": "帮助",
  "Image": "图片",
  "Link": "链接",
  "Source code": "源代码",
  "OK": "确定",
  "Cancel": "取消",
  "Save": "保存",
  "Delete": "删除",
  "Cut": "剪切",
  "Copy": "复制",
  "Paste": "粘贴",
  "Select all": "全选",
  "Bold": "加粗",
  "Italic": "斜体",
  "Underline": "下划线",
  "Strikethrough": "删除线",
  "Remove formatting": "清除格式",
  "Format Painter": "格式刷",
  "Align left": "左对齐",
  "Align center": "居中",
  "Align right": "右对齐",
  "Justify": "两端对齐",
  "Numbered list": "编号列表",
  "Bulleted list": "项目列表",
  "Decrease indent": "减少缩进",
  "Increase indent": "增加缩进",
  "Font": "字体",
  "Font size": "字号",
  "Text color": "文字颜色",
  "Background color": "背景色",
  "Redo": "重做",
  "Undo": "撤销",
  "Superscript": "上标",
  "Subscript": "下标",
  "Insert/edit image": "插入/编辑图片",
  "Upload": "上传",
  "Browse for an image": "浏览图片",
  "Alternative description": "替代文本",
  "Dimensions": "尺寸",
  "Width": "宽度",
  "Height": "高度",
  "Insert/edit link": "插入/编辑链接",
  "Text to display": "显示文字",
  "Url": "网址",
  "Open link in...": "打开链接",
  "Target": "目标",
  "None": "无",
  "New window": "新窗口",
  "Remove link": "移除链接",
  "Table": "表格",
  "Insert table": "插入表格",
  "Rows": "行",
  "Columns": "列",
  "Cell padding": "单元格内边距",
  "Cell spacing": "单元格间距",
  "Border": "边框",
  "Alignment": "对齐",
  "Caption": "标题",
  "Style": "样式",
  "Class": "类名",
  "Search": "搜索",
  "Replace": "替换",
  "Find and replace": "查找替换",
  "Close": "关闭",
  "Insert template": "插入模板",
  "Templates": "模板",
  "Document properties": "文档属性",
  "No color": "无色",
  "Custom color": "自定义颜色",
  "More colors": "更多颜色",
  "No": "否",
  "Yes": "是",
  "Are you sure?": "确定吗？",
  "Warning": "警告",
  "Error": "错误",
  "Drop an image here": "将图片拖放到此处",
  "Or": "或",
  "Browse for an image": "浏览选择图片",
  "Restore last draft": "恢复上次草稿",
  "Special characters": "特殊字符",
  "Source": "来源",
  "Insert code": "插入代码",
  "Language": "语言",
  "Keyboard shortcuts": "快捷键",
  "Media": "媒体",
  "Horizontal line": "水平线",
  "Page break": "分页符",
  "Nonbreaking space": "不间断空格",
  "Emoticons": "表情",
  "Anchor": "锚点"
});
