tinymce.addI18n('zh_CN',{
"Redo": "重做",
"Undo": "撤销",
"Cut": "剪切",
"Copy": "复制",
"Paste": "粘贴",
"Select all": "全选",
"New document": "新文档",
"Ok": "确定",
"Cancel": "取消",
"Visual aids": "网格线",
"Bold": "粗体",
"Italic": "斜体",
"Underline": "下划线",
"Strikethrough": "删除线",
"Superscript": "上标",
"Subscript": "下标",
"Clear formatting": "清除格式",
"Align left": "左对齐",
"Align center": "居中",
"Align right": "右对齐",
"Justify": "两端对齐",
"Bullet list": "项目列表",
"Numbered list": "编号列表",
"Decrease indent": "减少缩进",
"Increase indent": "增加缩进",
"Font": "字体",
"Font size": "字号",
"Image": "图片",
"File": "文件",
"Table": "表格",
"Link": "链接",
"Format": "格式",
"Tools": "工具",
"Fullscreen": "全屏",
"Code": "代码",
"Source code": "源代码",
"Save": "保存",
"Print": "打印",
"Page break": "分页符",
"Color": "颜色",
"Text color": "文字颜色",
"Background color": "背景颜色",
"Font color": "字体颜色",
"Table of Contents": "目录",
"Search": "搜索",
"Replace": "替换",
"Insert": "插入",
"Delete": "删除",
"Upload": "上传",
"Drop an image here": "将图片拖拽到此处",
"Image description": "图片描述",
"Alt text": "替代文本",
"Width": "宽",
"Height": "高",
"Style": "样式",
"Title": "标题",
"Target": "目标",
"URL": "URL",
"Open in new tab": "在新标签页中打开",
"Open link": "打开链接",
"Edit link": "编辑链接",
"Remove link": "删除链接",
"Checklist": "清单",
"Anchor": "锚点",
"Rows": "行",
"Columns": "列",
"Cell padding": "内边距",
"Cell spacing": "单元格间距",
"Row type": "行类型",
"Header": "头部",
"Footer": "底部",
"Body": "主体",
"Caption": "标题",
"Table caption": "表格标题",
"Left": "左",
"Center": "中",
"Right": "右",
"Cell type": "单元格类型",
"Scope": "范围",
"Horizontal align": "水平对齐",
"Vertical align": "垂直对齐",
"Insert table": "插入表格",
"Table class": "表格类",
"Border": "边框",
"Color picker": "颜色选择器",
"Add to dictionary": "添加到字典",
"Spelling": "拼写",
"Language": "语言",
"Spellcheck": "拼写检查",
"English": "英语",
"Chinese": "中文",
"Find": "查找",
"Find and replace": "查找和替换",
"Find whole words only": "全字匹配",
"Match case": "区分大小写",
"Keyboard shortcuts": "键盘快捷键"
});